FROM androidsdk/android-31

ARG UID
ARG GID

RUN apt -y install sudo
RUN usermod -u $UID android
RUN groupmod -g $GID android
RUN echo "android ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers
RUN sdkmanager --install "build-tools;30.0.3"
RUN sdkmanager --install "system-images;android-29;google_apis;x86_64"
RUN echo "no" | avdmanager --verbose create avd --force --name "nexus_5x_api29" --sdcard 2000M --device "Nexus 5X" --package "system-images;android-29;google_apis;x86_64"
USER android