FROM androidsdk/android-30

RUN apt -y install sudo
RUN groupadd -r -g $GID buildusr || true
RUN useradd -m -r -u $UID -g buildusr buildusr || true
RUN echo "android ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers
RUN sdkmanager --install "system-images;android-29;google_apis;x86_64"
RUN echo "no" | avdmanager --verbose create avd --force --name "nexus_5x_api29" --sdcard 2000M --device "Nexus 5X" --package "system-images;android-29;google_apis;x86_64"
USER android