FROM androidsdk/android-30

ARG UID
ARG GID
ARG KEEPITUP_KEYSTORE_FILE
ARG KEEPITUP_KEY_ALIAS
ARG KEEPITUP_KEYSTORE_PASS
ARG KEEPITUP_KEY_PASS
ENV KEEPITUP_KEYSTORE_FILE=$KEEPITUP_KEYSTORE_FILE
ENV KEEPITUP_KEY_ALIAS=$KEEPITUP_KEY_ALIAS
ENV KEEPITUP_KEYSTORE_PASS=$KEEPITUP_KEYSTORE_PASS
ENV KEEPITUP_KEY_PASS=$KEEPITUP_KEY_PASS
ENV BUILD_TOOLS_PATH=$ANDROID_SDK_ROOT/build-tools/30.0.2

RUN usermod -u $UID android
RUN groupmod -g $GID android
USER android