FROM androidsdk/android-30

ARG UID
ARG GID
ARG KEEPITUP_KEYSTORE
ARG KEEPITUP_SIGNING_PROPERTIES
ENV KEEPITUP_KEYSTORE=$KEEPITUP_KEYSTORE
ENV KEEPITUP_SIGNING_PROPERTIES=$KEEPITUP_SIGNING_PROPERTIES

RUN usermod -u $UID android
RUN groupmod -g $GID android
USER android